### ISSUE TITLE
gateway.php启动后 register.php报错 请问是什么原因？

### ISSUE THREAD

**Issue by luyulantian** [xielei/swoole-worker#1]
Fatal error: Uncaught TypeError: Argument 2 passed to Xielei\Swoole\Service::{closure}() must be an instance of Swoole\Server\Event, int given in /mnt/d/linuxdev/swooler/vendor/xielei/swoole-worker/src/reload/register.php:27
Stack trace:
#0 [internal function]: Xielei\Swoole\Service->{closure}()
#1 /mnt/d/linuxdev/swooler/vendor/xielei/swoole-worker/src/Service.php(239): call_user_func()
#2 /mnt/d/linuxdev/swooler/vendor/xielei/swoole-worker/src/Service.php(207): Xielei\Swoole\Service->emit()
#3 {main}
  thrown in /mnt/d/linuxdev/swooler/vendor/xielei/swoole-worker/src/reload/register.php on line 27

**Comment by xielei** [comment]
你是不是用的v1.0.3？

**Comment by luyulantian** [comment]
最近在寻找swoole分布式的框架，今天刚好看到你这个项目，这个架构太好了，非常不错，强烈支持。

之前用的swoole 4.5 有点问题 升级4.6.7就没有上面的问题，worker.php报了一个检查配置项的警告，请问这个有影响么。目前register.php,gateway.php,worker.php都启动了，不知道后面怎么测试。

examples\worker.php有个小问题：$worker->$worker->start();


另外请教个问题，最近在做一个物联网的项目，我可以用这个框架放到生产环境么，5W-10W设备 TCP协议能支持么。

如果可以的话请加下我的Q2475614099，可付费咨询。

Warning: unsupported option [log_file ] in @swoole-src/library/core/Server/Helper.php on line 165
#0  Swoole\Server\Helper::checkOptions()
#1  Swoole\Server\Port->set()
#2  Swoole\Server->set() called at [/mnt/d/linuxdev/swoolers/src/Service.php:212]
#3  Xielei\Swoole\Service->startServer() called at [/mnt/d/linuxdev/swoolers/src/Service.php:84]
#4  Xielei\Swoole\Service->Xielei\Swoole\{closure}()
#5  call_user_func() called at [/mnt/d/linuxdev/swoolers/src/Cli.php:91]
#6  Xielei\Swoole\Cli->execCommand() called at [/mnt/d/linuxdev/swoolers/src/Cli.php:61]
#7  Xielei\Swoole\Cli->listen() called at [/mnt/d/linuxdev/swoolers/src/Cli.php:43]
#8  Xielei\Swoole\Cli->start() called at [/mnt/d/linuxdev/swoolers/examples/worker.php:25]
PHP Warning:  unsupported option [stats_file ] in @swoole-src/library/core/Server/Helper.php on line 165

**Comment by luyulantian** [comment]
我搞清楚了 用event_worker_test.php 换掉event_worker测试

**Comment by xielei** [comment]
在swoole4.6.4下开发的，很早的swoole可能有些参数不支持，另外10万链接不算多

**Comment by huifeideyu001** [comment]
Api::sendToUid($uid,'sendToUid success');
使用这个方法，发送不成功怎么回事呀，使用Api::sendToClient($client, "bindUid success\n");发送正常

**Comment by xielei** [comment]
> Api::sendToUid($uid,'sendToUid success');
> 使用这个方法，发送不成功怎么回事呀，使用Api::sendToClient($client, "bindUid success\n");发送正常，已经进行Api::bindUid($client, $uid);绑定

你的版本是多少呢，是不是1.0.5最新版，不要用开发版

**Comment by huifeideyu001** [comment]
"name": "xielei/swoole-worker",
"version": "1.0.0",
"version_normalized": "1.0.0.0",
不是最新的，我是用composer require xielei/swoole-worker下载的

**Comment by xielei** [comment]
> "name": "xielei/swoole-worker",
> "version": "1.0.0",
> "version_normalized": "1.0.0.0",
> 不是最新的，我是用composer require xielei/swoole-worker下载的

composer update 更新到最新版 1.0.5

**Comment by huifeideyu001** [comment]
好的，谢谢
