### ISSUE TITLE
启动之后,连接WS就提示这个错误protocol decode failure! buffer:

### ISSUE THREAD

**Issue by linxianfu** [xielei/swoole-worker#2]
Fatal error:  Uncaught exception 'Exception' with message:
protocol decode failure! buffer:
thrown in /www/test/vendor/xielei/swoole-worker/src/Protocol.php on line 39
Trace:
#0 /www/test/vendor/xielei/swoole-worker/src/Worker.php(78): Xielei\Swoole\Protocol::decode('')

**Comment by xielei** [comment]
版本多少？升级到最新版
