### ISSUE TITLE
启动worker文件 显示这样的错误#0  Swoole\Server\Helper::checkOptions()

### ISSUE THREAD

**Issue by linxianfu** [xielei/swoole-worker#3]
the service is running with daemonize
> #0  Swoole\Server\Helper::checkOptions()
#1  Swoole\Server\Port->set()
#2  Swoole\Server->set() called at [/www/test/vendor/xielei/swoole-worker/src/Service.php:212]
#3  Xielei\Swoole\Service->startServer() called at [/www/test/vendor/xielei/swoole-worker/src/Service.php:73]
#4  Xielei\Swoole\Service->Xielei\Swoole\{closure}()
#5  call_user_func() called at [/www/test/vendor/xielei/swoole-worker/src/Cli.php:99

**Comment by xielei** [comment]
确保是最新版

**Comment by xielei** [comment]
知道了 文档上面 的'log_file '里面有个空格 把这个空格删掉。
