### ISSUE TITLE
Tcp发送16进制错误

### ISSUE THREAD

**Issue by wuguangping** [xielei/swoole-worker#5]
![图片](https://user-images.githubusercontent.com/7068986/144705789-cf654fad-d650-4b66-97e4-51f33525f910.png)
环境
php 7.3.25 swoole 4.6.7
php 7.4.25 swoole 4.8.2

**Comment by wuguangping** [comment]
要转2进制发送吗

**Comment by heimi** [comment]
PHP 8.0.11
Swoole 4.8.3
也是同样的问题， 看了一下是json_encode不成功。 sendToProcess是不是不需要转换

**Comment by xielei** [comment]
> ![图片](https://user-images.githubusercontent.com/7068986/144705789-cf654fad-d650-4b66-97e4-51f33525f910.png) 环境 php 7.3.25 swoole 4.6.7 php 7.4.25 swoole 4.8.2

bug. 稍后修复

**Comment by xielei** [comment]
> 



> PHP 8.0.11 Swoole 4.8.3 也是同样的问题， 看了一下是json_encode不成功。 sendToProcess是不是不需要转换

bug 稍后修复
